name = "my-new-blog"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-29"

[vars]
PUBLIC_SITE_URL = "https://havenofe1sar.cn"
PUBLIC_SUPABASE_URL = "https://govdfuzkcnbsnvozzqwb.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_OmoC6JlLIwPfcj0SsEXxNQ_fP3M_VO7"

[env.production.vars]
PUBLIC_SITE_URL = "https://havenofe1sar.cn"
PUBLIC_SUPABASE_URL = "https://govdfuzkcnbsnvozzqwb.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_OmoC6JlLIwPfcj0SsEXxNQ_fP3M_VO7"
